from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from .models import DATA_DIR

ROOT_DIR = DATA_DIR.parent
EXPORT_DIR = ROOT_DIR / "exports"
TARGETS = {"litellm", "gateway", "all"}


@lru_cache(maxsize=1)
def load_aliases() -> dict[str, Any]:
    with (DATA_DIR / "litellm_model_aliases.json").open(encoding="utf-8") as f:
        return json.load(f)["aliases"]


@lru_cache(maxsize=1)
def load_enterprise_templates() -> dict[str, Any]:
    with (DATA_DIR / "enterprise_gateway_templates.json").open(encoding="utf-8") as f:
        return json.load(f)


def export_enterprise(target: str = "all", output_dir: Path | None = None) -> list[Path]:
    if target not in TARGETS:
        raise ValueError("target must be litellm, gateway, or all")

    base = output_dir or EXPORT_DIR
    files: dict[Path, str] = {}
    if target in {"litellm", "all"}:
        files.update(_litellm_files(base / "litellm"))
    if target in {"gateway", "all"}:
        files.update(_gateway_files(base / "gateway"))

    written = []
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
        written.append(path)
    return written


def format_export_result(paths: list[Path]) -> str:
    return "\n".join(["Generated enterprise export files:", *[f"- {_display_path(path)}" for path in paths]])


def _litellm_files(base: Path) -> dict[Path, str]:
    aliases = load_aliases()
    templates = load_enterprise_templates()
    return {
        base / "config.example.yaml": _litellm_config(aliases),
        base / "model_aliases.example.yaml": _model_aliases_yaml(aliases),
        base / "team_budget_policy.example.yaml": _team_budget_yaml(templates["team_budget_groups"]),
        base / "virtual_keys.example.md": _virtual_keys_md(templates["team_budget_groups"]),
    }


def _gateway_files(base: Path) -> dict[Path, str]:
    templates = load_enterprise_templates()
    return {
        base / "routing_policy.example.yaml": _routing_policy_yaml(templates["routing_policies"]),
        base / "context_policy.example.yaml": _context_policy_yaml(),
        base / "guardrails_policy.example.yaml": _guardrails_yaml(templates["guardrails"]),
        base / "observability_policy.example.yaml": _observability_yaml(templates["observability_fields"]),
        base / "devspace_integration_contract.md": _integration_contract_md(),
    }


def _litellm_config(aliases: dict[str, Any]) -> str:
    rows = []
    for alias, spec in aliases.items():
        for index, model in enumerate(spec["models"], 1):
            rows.extend(
                [
                    f"  - model_name: {alias}",
                    "    litellm_params:",
                    f"      model: CHANGE_ME_PROVIDER/{_slug(model)}",
                    "      api_key: os.environ/OPENAI_API_KEY",
                    f"      rpm: CHANGE_ME_RPM_{index}",
                    f"      tpm: CHANGE_ME_TPM_{index}",
                    "    model_info:",
                    f"      devspace_tier: {spec['tier']}",
                    f"      source_model: \"{model}\"",
                ]
            )
    return "\n".join(
        [
            "# Example LiteLLM-style config generated by AgenticRouter.",
            "# Placeholder only. Replace CHANGE_ME values outside this repo.",
            "model_list:",
            *rows,
            "",
            "router_settings:",
            "  routing_strategy: simple-shuffle",
            "  fallbacks:",
            "    - devspace-cheap: [devspace-mid]",
            "    - devspace-mid: [devspace-advanced]",
            "    - devspace-live-prod: [devspace-advanced]",
            "    - devspace-security: [devspace-advanced]",
            "  # context_window_fallbacks:",
            "  #   - devspace-mid: [devspace-advanced]",
            "  redis_host: os.environ/CHANGE_ME_REDIS_HOST",
            "",
            "litellm_settings:",
            "  drop_params: true",
            "  request_timeout: CHANGE_ME_TIMEOUT_SECONDS",
            "  success_callback: [CHANGE_ME_LOGGER]",
            "  failure_callback: [CHANGE_ME_ALERTING]",
            "",
            "general_settings:",
            "  master_key: os.environ/LITELLM_MASTER_KEY",
            "  store_model_in_db: false",
            "  alerting: CHANGE_ME_ALERTING_TARGET",
            "  proxy_budget_rescheduler_min_time: CHANGE_ME_MINUTES",
            "",
            "environment_variables:",
            "  OPENAI_API_KEY: os.environ/OPENAI_API_KEY",
            "  ANTHROPIC_API_KEY: os.environ/ANTHROPIC_API_KEY",
            "  LITELLM_MASTER_KEY: os.environ/LITELLM_MASTER_KEY",
            "",
            "budget_placeholders:",
            "  default_team_budget: CHANGE_ME_MONTHLY_BUDGET",
            "  default_rpm: CHANGE_ME_RPM",
            "  default_tpm: CHANGE_ME_TPM",
            "",
            "logging_placeholders:",
            "  mode: metadata_only",
            "  sink: CHANGE_ME_LOGGING_SINK",
            "  do_not_log_prompt_bodies_for_sensitive_tasks: true",
        ]
    )


def _model_aliases_yaml(aliases: dict[str, Any]) -> str:
    lines = ["aliases:"]
    for alias, spec in aliases.items():
        lines.extend([f"  {alias}:", f"    tier: {spec['tier']}", "    models:"])
        lines.extend(f"      - \"{model}\"" for model in spec["models"])
    return "\n".join(lines)


def _team_budget_yaml(groups: dict[str, Any]) -> str:
    lines = ["team_budget_policy:"]
    for group, spec in groups.items():
        lines.extend(
            [
                f"  {group}:",
                "    allowed_aliases:",
                *[f"      - {alias}" for alias in spec["allowed_aliases"]],
                f"    monthly_budget: {spec['budget']}",
                f"    rpm: {spec['rpm']}",
                f"    tpm: {spec['tpm']}",
                f"    human_review_rule: {spec['human_review_rule']}",
                f"    logging_level: {spec['logging_level']}",
            ]
        )
    return "\n".join(lines)


def _virtual_keys_md(groups: dict[str, Any]) -> str:
    rows = [
        "# Virtual Keys Example",
        "",
        "Placeholder only. Create real keys in the gateway, not in this repo.",
        "",
        "| Group | Virtual key placeholder | Allowed aliases |",
        "| --- | --- | --- |",
    ]
    for group, spec in groups.items():
        rows.append(f"| {group} | CHANGE_ME_VIRTUAL_KEY_{group.upper()} | {', '.join(spec['allowed_aliases'])} |")
    return "\n".join(rows)


def _routing_policy_yaml(policies: list[dict[str, Any]]) -> str:
    lines = ["routing_policy:"]
    for policy in policies:
        lines.extend(
            [
                f"  - task_class: {policy['task_class']}",
                f"    risk_level: {policy['risk_level']}",
                f"    default_model_alias: {policy['default_model_alias']}",
                "    allowed_fallback_aliases:",
                *[f"      - {alias}" for alias in policy["allowed_fallback_aliases"]],
                f"    human_review_required: {str(policy['human_review_required']).lower()}",
                f"    context_size: {policy['context_size']}",
                "    forbidden_context:",
                *[f"      - {item}" for item in policy["forbidden_context"]],
                "    escalation_triggers:",
                *[f"      - {item}" for item in policy["escalation_triggers"]],
            ]
        )
    return "\n".join(lines)


def _context_policy_yaml() -> str:
    return "\n".join(
        [
            "context_policy:",
            "  default: smallest_useful_context",
            "  include:",
            "    - route_id",
            "    - project_name",
            "    - task_class",
            "    - touched_files_or_safe_patterns",
            "    - context_pack",
            "  exclude:",
            "    - secrets",
            "    - PII",
            "    - production logs",
            "    - unrelated repositories",
            "  summarize_large_files: true",
            "  include_repo_map_when_files_missing: true",
        ]
    )


def _guardrails_yaml(guardrails: list[str]) -> str:
    return "\n".join(["guardrails_policy:", *[f"  - {item}" for item in guardrails]])


def _observability_yaml(fields: list[str]) -> str:
    return "\n".join(
        [
            "observability_policy:",
            "  log_fields:",
            *[f"    - {field}" for field in fields],
            "  sensitive_task_logging:",
            "    do_not_log_prompt_bodies: true",
            "    do_not_log_context_bodies: true",
            "    do_not_log_secrets_or_pii: true",
            "  retention:",
            "    metadata_days: CHANGE_ME_RETENTION_DAYS",
            "    sensitive_metadata_days: CHANGE_ME_SENSITIVE_RETENTION_DAYS",
        ]
    )


def _integration_contract_md() -> str:
    return "\n".join(
        [
            "# DevSpace Integration Contract",
            "",
            "AgenticRouter is the policy brain. A LiteLLM-style gateway is the traffic layer.",
            "",
            "## Request Metadata",
            "",
            "- route_id",
            "- project_name",
            "- task_class",
            "- recommended_model_alias",
            "- model_tier",
            "- risk_level",
            "- context_size",
            "- human_review_required",
            "",
            "## Safety Contract",
            "",
            "- Send sanitized context only.",
            "- Never send secrets, PII, records, tenant IDs, USB serials, or production logs.",
            "- Require human approval before live-prod deployment or sensitive/security changes.",
            "- Source verification is required for public official content.",
        ]
    )


def _slug(model: str) -> str:
    return model.lower().replace(".", "-").replace(" ", "-")


def _display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT_DIR).as_posix()
    except ValueError:
        return path.as_posix()
